### ISSUE TITLE
there was some exception where pares some section log 

### ISSUE THREAD

**Issue by houlmate** [luchuanbaker/ChkBugReportCore#1]
maybe u can ignore the parse exception, and apply the operation manual and instruction documentation

**Comment by luchuanbaker** [comment]
This is a very old project which is copied from https://github.com/sonyxperiadev/ChkBugReport，the original project is not maintained any more since 2 years ago.
The bug report file of android has changed a lot, so what I can do is just forking the repo、fixing some bugs and etc.
So you can do the same things like me, because it is open source.
Maybe I don't have enough time to do these things, and I am looking forward to seeing your performance!!
Come on!
